# Generated by Django 5.2.15 on 2026-06-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
